import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/page";
import Footer from "./components/footer/page";
import AboutUs from "./components/pages/aboutus/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Anu Kitchen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth bg-[#1E1E1E]">
      <body className={inter.className}>
        <Navbar />
        {children}
        <AboutUs />
        <Footer />
      </body>
    </html>
  );
}
